spring:
    config:
        import: application-prod.yml
    profiles:
        active: default
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5431/security_db
        username: postgres
        password: 748295
    security:
      user:
          name: zzz
          password: zzz
    main:
        banner-mode: off
server:
    port: 8080

logging.level.org.springframework.security: TRACE
logging.pattern.console: LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n
